- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: check for updates (yum)
            yum: list=updates update_cache=true
            register: yumoutput
            when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
          - debug:
              msg: "{{ yumoutput.results | map(attribute='name') | list }}"
