- hosts: all
  gather_facts: false
  become: yes
  user: root

  tasks:
  - name: List Available Patches (Non-Kernel)
    yum:
      list: updates
      update_cache: true
      exclude: kernel*
    register: yumoutput

  - debug: msg="{{ inventory_hostname}} {{ yumoutput.results }}"
